### ISSUE TITLE
Only update the Teams Machine-Wide Installer

### ISSUE THREAD

**Issue by jkman2** [microsoft/TeamsMsiOverride#10]
How to update the the Teams Machine-Wide Installer but not trigger any updates for per-user instances of Teams?

**Comment by chtartMSFT** [comment]
The script by default will not allow this.  You can set AllowMsiOverride to 0 but then the script will exit when it sees that value.
If you remove this call in the script, it would skip checking/setting the registry key:

```
# Check and set AllowMsiOverride key
CheckPolicyKey
```
