### ISSUE TITLE
Support Intune Deployment?

### ISSUE THREAD

**Issue by LBXComputers** [microsoft/TeamsMsiOverride#11]
Is there a way to get this script to run via intune? It requires parameter so cannot use the “scripts” functionality.

**Comment by chtartMSFT** [comment]
I don't know the exact steps.  The script supports the Package type which allows you to place the script and MSIs in a single location that can be bundled into a package that is pushed by deployment software.  Beyond that the exact steps to execute the package would depend on the deployment software.

**Comment by LBXComputers** [comment]
I’ve managed to deploy it via Endpoint writing a wrapper script to download this script and unzip it before executing it and then deleting the temporary files. Would be easier if the script just executed using the CDN option by default instead of being a mandatory parameter with no default.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
