### ISSUE TITLE
Support for noAutoStart

### ISSUE THREAD

**Issue by Orava2** [microsoft/TeamsMsiOverride#12]
Hello

The current script does not support the noAutoStart parameters. 

I tried to edit the line https://github.com/microsoft/TeamsMsiOverride/blob/main/src/CheckMsiOverride.ps1#L859C54-L859C54 to
`$msiExecArgs = "$msiExecFlags `"$toMsi`" /quiet OPTIONS='noAutoStart=true ALLUSERS=1' /l*v $env:TEMP\msiOverrideCheck_msiexec.log"`
but this did not work as I expected. The file C:\Program Files (x86)\Teams Installer\setup.json was modified but noAutoStart was added two times.
`{"noAutoStart":false,"'noAutoStart":"true"}`
```[tasklist]
### Tasks
```

**Comment by chtartMSFT** [comment]
Given this script was mainly designed to update existing installs, that parameter was not included.
That said, your modification contains an error.  ALLUSERS=1 is an MSIExec parameter, not an option to be included.
You'll notice it is including the single quote (') in the parameter name, so I'm assuming it is interpreting the name as 'noAutoStart
The single quote is not correct here, as we expect double quotes, so you should use escaped double quotes in the string, and leave the ALLUSERS=1 outside of it.
msiexec /i Teams_windows.msi OPTIONS="noAutoStart=true" ALLUSERS=1
