### ISSUE TITLE
Use -UseBasicParsing flag on IWR Calls

### ISSUE THREAD

**Issue by ahambidg** [microsoft/TeamsMsiOverride#5]
With the EOL of IE and many companies disabling it, it's best to add the `-UseBasicParsing` flag on the Invoke-WebRequest calls so that they don't fail.

**Comment by chtartMSFT** [comment]
Thank you for the suggestion, there is a test version on #4 which has this implemented already.  I have not yet completed the testing to fully release that version yet, but feel free to test it. I will leave this open until that ships.

**Comment by chtartMSFT** [comment]
I pushed the version with this fix live now: 1.0.2110.2101
