### ISSUE TITLE
Slow Download Speeds with Invoke-WebRequest

### ISSUE THREAD

**Issue by ahambidg** [microsoft/TeamsMsiOverride#6]
Due to [this PowerShell 5.1 bug](https://github.com/PowerShell/PowerShell/issues/2138) (which is not going to be fix/backported from 7) should the download lines utilizing Invoke-WebRequest be changed to either set `$ProgressPreference = 'SilentlyContinue'` or the following .NET web client instead?

`$wc = New-Object System.Net.WebClient; $wc.DownloadFile("https://github.com/dotnet/corefx/archive/master.zip", "C:\Users\crispop\Desktop\master.zip") }`

**Comment by chtartMSFT** [comment]
Thank you for the suggestion.  There is a test version on #4 which has this implemented already.  Please feel free to test that version until I have it ready for full release. I will leave this open until that version ships.

**Comment by chtartMSFT** [comment]
I pushed the version with this fix live now: 1.0.2110.2101
