### ISSUE TITLE
CheckMsiOverride.ps1 - Powershell 7 Fail On Event Log Cmdlets

### ISSUE THREAD

**Issue by mattcargile** [microsoft/TeamsMsiOverride#7]
Fails partly on Powershell 7.2.1. Still all appears to work correctly though. Need to replace with `New-WinEvent` for both creation and writing it appears.

```powershell
New-EventLog: C:\Users\user\OneDrive\Main\SoftwareMisc\TeamsMsiOverride\CheckMsiOverride.ps1:623
Line |
 623 |  New-EventLog -LogName Application -Source $EventLogSource -ErrorActio …
     |  ~~~~~~~~~~~~
     | The term 'New-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.
```

```powershell
Write-EventLog: C:\Users\user\OneDrive\Main\SoftwareMisc\TeamsMsiOverride\CheckMsiOverride.ps1:814
Line |
 814 |      Write-EventLog -LogName Application -Source $EventLogSource -Cate …
     |      ~~~~~~~~~~~~~~
     | The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a
     | path was included, verify that the path is correct and try again.
```

**Comment by chtartMSFT** [comment]
There is a prerelease version which fixes this:
https://github.com/microsoft/TeamsMsiOverride/releases/tag/v1.0.2311.3001

This release is not signed as my internal infrastructure to support signing it is no longer functional.
With the move to New Teams, this script will soon no longer be needed as the install process for New Teams is very different, so there was not really much point in rebuilding the infrastructure.
This just means this pre-release version, and any others that might come later will not be signed, so you will need to set/manage you script execution policy properly.
