### ISSUE TITLE
Teams Wide Installer of Machines with Multiple Users

### ISSUE THREAD

**Issue by ruiz12031** [microsoft/TeamsMsiOverride#8]
Hello:

I am trying to update the Teams wide installer with the script. I am using the following command:

_Powershell.exe .\CheckMsiOverride.ps1 -Type Package -OverrideVersion 1.5.00.17656 -AllowInstallOverTopExisting -FixRunKey -OverwritePolicyKey -Uninstall32Bit_

The issue I am seeing is machines where multiple users log into (profiles already cached and created) when a user logs in immediately after update, no issue. When a 2nd user logs in, that user is reporting teams is missing and its not auto installing. Wondering if anyone else has seen this issue before. Thanks

TeamsMSIOverride log below:

_Start Trace 08/03/2022 22:47:09
Script Version 1.0.2110.2101
Parameters Type: Package, PreviewRing: False, BaseShare: , OverrideVersion: 1.5.00.17656, MsiFileName: , AllowInstallOvertopExisting: True, OverwritePolicyKey: False, FixRunKey: True
Environment IsSystemAccount: True, IsOS64Bit: True
Removing temp folder C:\WINDOWS\TEMP\TeamsMsiOverrideCheck
The policy key AllowMsiOverride is not set, setting HKLM:\Software\Policies\Microsoft\Office\16.0\Teams\AllowMsiOverride to 1...
AllowMsiOverride policy is set to True
ProductsRegLM: 3180FA93B7AF0684DAEB399B2B419B41 AAB6F137689A4A549863C7A3AAAA67B0
ProductsRegCU:
About to uninstall 32-bit MSI using this msiexec command:
msiexec.exe /X {39AF0813-FA7B-4860-ADBE-93B9B214B914} /quiet /l*v C:\WINDOWS\TEMP\msiOverrideCheck_msiexecUninstall.log
MsiExec completed successfully.
Teams Machine-Wide Installer was not found.
UninstallReg1: {731F6BAA-A986-45A4-8936-7C3AAAAA760B}
UninstallReg2:
ProductsRegLM: AAB6F137689A4A549863C7A3AAAA67B0
ProductsRegCU:
PackageName: Teams_windows_x64.msi
Using working directory to aquire the new MSI...
Working Directory: C:\WINDOWS\ccmcache\70
Using 64-bit MSI from working directory
Target Teams Machine-Wide Installer version is 1.5.00.17656
This will be an override update
Copying C:\WINDOWS\ccmcache\70\Teams_windows_x64.msi to C:\WINDOWS\TEMP\TeamsMsiOverrideCheck\Teams_windows_x64.msi...
About to perform deployment using this msiexec command:
msiexec.exe /fav "C:\WINDOWS\TEMP\TeamsMsiOverrideCheck\Teams_windows_x64.msi" /quiet ALLUSERS=1 /l*v C:\WINDOWS\TEMP\msiOverrideCheck_msiexec.log
MsiExec completed successfully.
Rewriting the HKLM Run key with "C:\Program Files (x86)\Teams Installer\Teams.exe" --checkInstall --source=default
New Teams Machine Installer version is 1.5.00.17656
Deployment successful, installer is now at target version!
Removing temp folder C:\WINDOWS\TEMP\TeamsMsiOverrideCheck
End Trace 08/03/2022 22:47:13_

**Comment by chtartMSFT** [comment]
Teams was installed Per-Machine, which this script does not support.  A Per-Machine install has ALLUSER=1 as a MSI parameter to have Teams installed into Program Files.  It is only supported for VDI use cases.
If Teams is installed Per-Machine this script should not be used.
