### ISSUE TITLE
Uninstall32Bit not working as expected

### ISSUE THREAD

**Issue by MAnECiaC** [microsoft/TeamsMsiOverride#9]
The _Uninstall32Bit_ option only seems to work if the 64-bit version is also already installed. If I don't misunderstand, the function _GetProductsKey_ only returns an array if both versions are installed?!

```
$productsKey = GetProductsKey
if($productsKey -is [array])
{
    # If switch is passed, uninstall the 32 bit MSI before we perform the upgrade on 64 bit.
    if($Uninstall32Bit)
    {
```

Could this be changed so that the script could be used to switch from 32-bit to 64-bit?

**Comment by chtartMSFT** [comment]
There is a prerelease version which has these changes:
https://github.com/microsoft/TeamsMsiOverride/releases/tag/v1.0.2311.3001

This release is not signed as my internal infrastructure to support signing it is no longer functional.
With the move to New Teams, this script will soon no longer be needed as the install process for New Teams is very different, so there was not really much point in rebuilding the infrastructure.
This just means this pre-release version, and any others that might come later will not be signed, so you will need to set/manage you script execution policy properly.
